### ISSUE TITLE
Broken with recent nightly

### ISSUE THREAD

**Issue by ajsyp** [vorot93/gen-stream#1]
gen-stream no longer builds on recent nightlies (for example, rustc 1.41.0-nightly (53712f863 2019-11-21)). The error is:

```
error[E0603]: function `set_task_context` is private
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/gen-stream-0.2.3/src/lib.rs:80:18
   |
80 |     std::future::set_task_context,
   |                  ^^^^^^^^^^^^^^^^
```

Looks like the `set_task_context` is no longer exposed by the `gen_future` feature gate. Any thoughts on how we should use this crate going forward?

**Comment by vorot93** [comment]
The direct generator-based approach was good in the nightlies' times. Now it's time to move to another crate compatible with stable async/await. [async-stream](https://github.com/tokio-rs/async-stream) and [genawaiter](https://github.com/whatisaphone/genawaiter) in particular stick out.
